# Generated by Django 4.1.2 on 2022-10-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_page_number_alter_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
