# Generated by Django 4.1.2 on 2022-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images_edited',
            field=models.BooleanField(default=True),
        ),
    ]
