# Generated by Django 4.1.2 on 2022-10-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_images_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='images_edited',
            field=models.BooleanField(default=False),
        ),
    ]
